print("hello")
print("My name is A")
print("My name is \"A\"")
print("My name is \"A\"")
print(4+5)
print(4-6)
print(4*6)
print(4/6)
print(6//4)
print(6**3)
print(6%4)
print(-11//4)
print("My name is Gouri")
print(6*5)
print(25**0.5)
n=input("What's your name?")
print(n)
M=(input("What's your surname?"))
print(M)
z=input("Enter you college name")
print(z)
p=int(input("Enter your PPS marks"))
j=int(input("Enter your maths marks"))
avg=(p+j)*0.5
print(avg)

