print("Problem statement 2:")
print('''Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
Fo this problem n=4million=4,000,000''')
#1million=1,000,000

def fibb(n):
    l=[]
    n1=0
    n2=1
    i=0
    while (True):
        s=n1+n2
        if (s>=n):
            break
        else:
            l.append(s)
            c=n2
            n2=s
            n1=c
            i+=1
    sum=0
    for i in l:
        if (i%2==0):
            sum+=i
    print(sum)
n=int(input("Enter the value that you don't want the terms in the fibbonacci term to exceed:"))
fibb(n)
